import Head from "next/head";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import CryptoDetails from "@/components/CryptoDetails";
import axios from "axios";

export default function CryptoSymbol({ data }: any) {
  console.log(data);

  return (
    <>
      <Head>
        <title>Stock Pulse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home-container">
        <Header />
        <Sidebar />
        <CryptoDetails currencyData={data} />
      </main>
    </>
  );
}

export const getServerSideProps = async (context: any) => {
  try {
    const today = new Date()
    const yesterday = new Date(today)
    
    yesterday.setDate(yesterday.getDate() - 1)
    
    const todayFormat = today.getFullYear() + "-" + (today.getMonth()+1).toString().padStart(2,'0') + "-" + today.getDate().toString().padStart(2,'0')
    const yesterdayFormat = yesterday.getFullYear() + "-" + (yesterday.getMonth()+1).toString().padStart(2,'0') + "-" + yesterday.getDate().toString().padStart(2,'0')

    const { symbol } = context.params;
    const apiKey = process.env.POLYGON_API_KEY;
    const url = `https://api.polygon.io/v2/aggs/ticker/X:${symbol}/range/1/day/${yesterdayFormat}/${todayFormat}?adjusted=true&sort=asc&limit=120&apiKey=${apiKey}`;

    const response = await axios.get(url);

    const data = response.data.results;

    return { props: { data } };
  } catch (err) {
    console.log("failed to fetch crypto details", err);
  }
};
