import Head from 'next/head';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import CryptoDetails from '@/components/CryptoDetails';

export default function CryptoSymbol() {
    return (
        <>
            <Head>
                <title>Stock Pulse</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="home-container">
                <Header />
                <Sidebar />
                <CryptoDetails />
            </main>
        </>
    );
}
