import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import { useRouter } from "next/router";
import { cryptoSymbol } from "crypto-symbol";
import { useEffect, useState } from "react";
import { Toaster } from "react-hot-toast";

const { nameLookup } = cryptoSymbol({});

export default function Layout({ children }: any) {
  const router = useRouter();
  const [title, setTitle] = useState("");

  useEffect(() => {
    // const { pathname, query } = router;
    // if (pathname === '/') return setTitle('');
    // const name = nameLookup(query.symbol as string);
    // setTitle('- ' + name || '');
  }, [router.pathname]);

  const dontNeedLayout = () =>
    router.pathname === "/login" || router.pathname === "/";

  return (
    <>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap"
          rel="stylesheet"
        />
        <title>Stock Pulse {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!dontNeedLayout() ? (
        <>
          <main className="home-container">
            <Sidebar />
            <section className="main-container">{children}</section>
          </main>
          <Toaster position="bottom-center" />
        </>
      ) : (
        children
      )}
    </>
  );
}
