import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import { connectToAlpacaStream } from '@/websocket';
import MainContent from '@/components/MainContent';
import Head from 'next/head';
import { useEffect, useState } from 'react';
// import useWebSockets from '@/hooks/useWebSockets';

export default function Home() {
    // const { crypto } = useWebSockets(['BTCUSD']);
    const [crypto, setCrypto] = useState(null);

    useEffect(() => {
        console.log(connectToAlpacaStream(['BTCUSD']));
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="home-container">
                {/* <div className="">{crypto}</div> */}
                <Header />
                <Sidebar />
                <MainContent></MainContent>
            </main>
        </>
    );
}

export async function getServerSideProps() {
    return {
        props: {
            price: 1,
            // price: data.last?.price,
        },
    };
}
