import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import { connectToAlpacaStream } from '@/websocket';
import MainContent from '@/components/MainContent';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
    useEffect(() => {
        connectToAlpacaStream();
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="home-container">
                <Header />
                <Sidebar />
                <MainContent></MainContent>
            </main>
        </>
    );
}
