import Head from 'next/head';
import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import MainContent from '@/components/MainContent';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

export default function Search() {
    const router = useRouter();

    useEffect(() => {
        console.log(router.query.crypto);
    });

    return (
        <>
            <Head>
                <title>Stock Pulse</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="home-container">
                <Header />
                <Sidebar />
                {/* <MainContent /> */}
            </main>
        </>
    );
}
